apiVersion: v1
kind: Secret
metadata:
  name: app-secret

type: Opaque
data:
  # echo -n 'admin' | base64
  db-pass: dnByb2RicGFzcw==
  # echo -n '1f2d1e2e67df' | base64
  rmq-pass: Z3Vlc3Q=

  rmq-user: cm9vdA==
